apiVersion: v1
kind: ConfigMap
metadata:
  name: pgvector-init
  namespace: aitp-data
data:
  init.sql: |
    CREATE EXTENSION IF NOT EXISTS vector;
    
    CREATE TABLE IF NOT EXISTS embeddings (
        id SERIAL PRIMARY KEY,
        content TEXT NOT NULL,
        metadata JSONB,
        embedding vector(1536),
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
    
    CREATE INDEX IF NOT EXISTS embeddings_embedding_idx 
    ON embeddings USING ivfflat (embedding vector_cosine_ops)
    WITH (lists = 100);
    
    CREATE INDEX IF NOT EXISTS embeddings_metadata_idx 
    ON embeddings USING GIN (metadata);
