apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: clickhouse
  namespace: aitp-data
spec:
  serviceName: clickhouse
  replicas: 3
  selector:
    matchLabels:
      app: clickhouse
  template:
    metadata:
      labels:
        app: clickhouse
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: clickhouse
              topologyKey: kubernetes.io/hostname
      containers:
        - name: clickhouse
          image: clickhouse/clickhouse-server:23.8-alpine
          ports:
            - containerPort: 8123
              name: http
            - containerPort: 9000
              name: native
          env:
            - name: CLICKHOUSE_DB
              value: aitp
            - name: CLICKHOUSE_USER
              value: aitp
            - name: CLICKHOUSE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: clickhouse-secret
                  key: password
          resources:
            requests:
              cpu: "2"
              memory: 4Gi
            limits:
              cpu: "4"
              memory: 8Gi
          volumeMounts:
            - name: data
              mountPath: /var/lib/clickhouse
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        storageClassName: ocs-storagecluster-ceph-rbd
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 100Gi
---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse
  namespace: aitp-data
spec:
  selector:
    app: clickhouse
  ports:
    - name: http
      port: 8123
    - name: native
      port: 9000
---
apiVersion: v1
kind: Secret
metadata:
  name: clickhouse-secret
  namespace: aitp-data
type: Opaque
stringData:
  password: "CHANGE_ME_CLICKHOUSE_PASSWORD"
