apiVersion: opstreelabs.in/v1alpha1
kind: MongoDBCluster
metadata:
  name: aitp-mongodb
  namespace: aitp-data
spec:
  clusterSize: 3
  kubernetesConfig:
    image: mongo:4.4
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: "2"
        memory: 4Gi
      requests:
        cpu: "1"
        memory: 2Gi
  mongoDBSecurity:
    mongoDBAdminUser: aitp-admin
    secretRef:
      name: mongodb-admin-password
      key: password
  storage:
    accessModes:
      - ReadWriteOnce
    storageClass: local-nvme
    storageSize: 50Gi
