apiVersion: v1
kind: Namespace
metadata:
  name: aitp-data
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: aitp-ai
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: aitp-ui
  labels:
    istio-injection: enabled
